import {defineConfig} from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    perf: "error",
    restriction: "error",
    style: "error",
  },
  env: {builtin: true},
  globals: {
    HTMLElement: "readonly",
    clearInterval: "readonly",
    customElements: "readonly",
    document: "readonly",
    process: "readonly",
    setInterval: "readonly",
    window: "readonly",
  },
  ignorePatterns: ["ingress-card.js", "dist/**", "node_modules/**"],
  jsPlugins: ["./oxlintPluginBraces.ts"],
  options: {
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ["*.ts", "src/build.ts"],
      rules: {"import/no-nodejs-modules": "off"},
    },
    {files: ["**/*.d.ts"], rules: {"import/unambiguous": "off"}},
    {
      files: ["test/**/*.ts", "src/build.ts"],
      rules: {"node/no-top-level-await": "off"},
    },
  ],
  plugins: [
    "eslint",
    "typescript",
    "oxc",
    "import",
    "jsdoc",
    "node",
    "promise",
    "unicorn",
  ],
  rules: {
    "arrow-body-style": ["error", "as-needed"],
    "braces/chain-requires-braces": "error",
    "braces/multi-or-nest": "error",
    "eslint/capitalized-comments": "off",
    "eslint/curly": "off",
    "eslint/func-style": ["error", "declaration", {allowArrowFunctions: true}],
    "eslint/id-length": "off",
    "eslint/init-declarations": "off",
    "eslint/max-params": "off",
    "eslint/max-statements": "off",
    "eslint/no-console": "off",
    "eslint/no-continue": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-restricted-imports": [
      "error",
      {patterns: [{regex: "^\\.\\.?/"}]},
    ],
    "eslint/no-ternary": "off",
    "eslint/no-undefined": "off",
    "eslint/no-void": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/sort-imports": ["error", {ignoreDeclarationSort: true}],
    "func-style": ["error", "declaration", {allowArrowFunctions: true}],
    "import/consistent-type-specifier-style": "off",
    "import/extensions": ["error", {ignorePackages: true}],
    "import/no-cycle": "error",
    "import/no-default-export": "off",
    "import/no-named-export": "off",
    "import/prefer-default-export": "off",
    "oxc/no-async-await": "off",
    "oxc/no-map-spread": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-magic-numbers": ["off"],
    "typescript/prefer-regexp-exec": "off",
    "typescript/promise-function-async": "off",
    "unicorn/catch-error-name": ["error", {name: "err"}],
    "unicorn/filename-case": ["error", {case: "camelCase"}],
    "unicorn/no-null": "off",
    "unicorn/switch-case-braces": ["error", "avoid"],
  },
});
